# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(db_index=True, max_length=200, verbose_name='新闻标题')),
                ('news_time', models.DateTimeField(auto_now_add=True, verbose_name='新闻时间')),
                ('news_source', models.CharField(blank=True, max_length=50, verbose_name='新闻来源')),
                ('news_abstract', models.CharField(blank=True, max_length=500, verbose_name='新闻摘要')),
                ('news_url', models.URLField(blank=True, null=True, verbose_name='新闻链接')),
                ('news_content', models.TextField(verbose_name='新闻内容')),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='用户组')),
                ('monitorkeys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.MonitorKeys', verbose_name='监控关键词')),
            ],
            options={
                'verbose_name': '爬虫数据',
                'verbose_name_plural': '爬虫数据',
                'db_table': 'crawler_news',
            },
        ),
        migrations.CreateModel(
            name='MonitorNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(db_index=True, max_length=200, verbose_name='新闻标题')),
                ('news_url', models.URLField(blank=True, null=True, verbose_name='新闻链接')),
                ('news_time', models.DateTimeField(auto_now_add=True, verbose_name='新闻时间')),
                ('news_source', models.CharField(blank=True, max_length=50, verbose_name='新闻来源')),
                ('news_content', models.TextField(verbose_name='新闻内容')),
                ('news_positive', models.BooleanField(verbose_name='正面新闻')),
                ('news_abstract', models.CharField(blank=True, max_length=500, verbose_name='新闻摘要')),
                ('monitorkeys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.MonitorKeys', verbose_name='监控关键词')),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻',
                'db_table': 'monitor_news',
            },
        ),
    ]
