# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 08:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlernews',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 19, 8, 5, 28, 722001, tzinfo=utc), verbose_name='新闻创建时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crawlernews',
            name='news_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='新闻时间'),
        ),
    ]
