# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20160519_0805'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.ImageField(null=True, upload_to='uploads/pic')),
            ],
        ),
    ]
