# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 08:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_releasenews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='releasenews',
            options={'verbose_name': '新闻(完整版)', 'verbose_name_plural': '新闻(完整版)'},
        ),
        migrations.AlterModelTable(
            name='releasenews',
            table='release_news',
        ),
    ]
