# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20160519_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasenews',
            name='release_path',
            field=models.ImageField(upload_to='pic/%Y/%m/%d/', verbose_name='新闻图片'),
        ),
    ]
