# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20160519_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasenews',
            name='release_path',
            field=models.ImageField(upload_to=news.models.get_uploads_path, verbose_name='新闻图片'),
        ),
    ]
