# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20160519_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasenews',
            name='release_path',
            field=models.ImageField(height_field=120, upload_to=news.models.get_uploads_path, verbose_name='新闻图片', width_field=200),
        ),
    ]
