# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 07:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keys_name', models.CharField(max_length=50, verbose_name='关键词名称')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='开始监控时间')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作人员')),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='用户组')),
            ],
            options={
                'verbose_name_plural': '关键词',
                'verbose_name': '关键词',
                'db_table': 'monitor_key',
            },
        ),
        migrations.CreateModel(
            name='SchedulePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_interval_time', models.PositiveSmallIntegerField(verbose_name='调用间隔小时')),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='用户组')),
            ],
            options={
                'verbose_name_plural': '调度计划',
                'verbose_name': '调度计划',
                'db_table': 'schedule_plan',
            },
        ),
    ]
